---
prefix_filter: []
max_length: 15
filename: "rus.txt"
train_size: 0.8
batch_size: 192
pretrained_input_tokenizer_name: "google/t5-efficient-mini" 
pretrained_output_tokenizer_name: "ai-forever/ruT5-base" 
